project:
  type: website
  output-dir: docs

website:
  title: "Bonnabelle Zabelle"
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
    logo: astroBonnie_pic.jpg
  repo-url: https://github.com/astroBonnie/astroBonnie.github.io
  repo-actions: [edit, source, issue]
  page-footer:
    left: "Copyright 2025, Bonnabelle Zabelle"
    right:
      - icon: github
        href: https://github.com/astroBonnie

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

